hexagon :- 
    write('   / \\  '),
    write('   / \\  '),
    write('   / \\  '),
    write('   / \\ '),nl,
    write(' /     \\'), 
    write(' /     \\'), 
    write(' /     \\'), 
    write(' /     \\'), nl,
    write('|  11   |'), 
    write('  2    |'), 
    write('  3    |'), 
    write('  4    |'), nl,
    write('|       |'), 
    write('       |'), 
    write('       |'), 
    write('       |'), nl,
    write(' \\     /'),
    write(' \\     /'),
    write(' \\     /'),
    write(' \\     /'), nl,
    write('   \\ /  '),
    write('   \\ /  '),
    write('   \\ /  '),
    write('   \\ /  '), nl,
    write('    |  5    | '),
    write(' 6    | '),
    write(' 7    | '),nl,
    write('    |       | '),
    write('      | '),
    write('      | '), nl,
    write('     \\     /'),
    write(' \\     /'),
    write(' \\     /'), nl,
    write('       \\ /'), 
    write('     \\ /'), 
    write('     \\ /'), nl.

list(List) :- List is [0,1].